import { StyleSheet } from 'react-native';
import { Colors, moderateScale, verticalScale } from '../../themes';

const styles = StyleSheet.create({
  weakPasswordTextStyles: {
    fontSize: moderateScale(18),
    fontWeight: '500',
    color: Colors.cinnabar,
  },
  signInOptionsContainer: {
    flexDirection: 'row',
    width: '40%',
    alignItems: 'center',
    justifyContent: 'space-evenly',
  },
  passwordValidationContainer: { width: '80%', padding: moderateScale(5) },
  passwordValidationTextStyles: {
    fontSize: moderateScale(17),
    fontWeight: '500',
    color: Colors.alto,
  },
  googleImageStyles: {
    marginTop: verticalScale(20),
    width: moderateScale(35),
    height: moderateScale(35),
  },
  weakPasswordContainer: {
    marginBottom: moderateScale(10),
    paddingHorizontal: moderateScale(7),
    paddingVertical: moderateScale(5),
    backgroundColor: Colors.cherub,
  },
  dontHaveAccountStyles: { fontSize: moderateScale(16), color: Colors.alto },
  dontHaveAccountContainer: {
    flexDirection: 'row',
    alignItems: 'baseline',
    justifyContent: 'center',
  },
  signUpText: { fontSize: moderateScale(15), color: Colors.cyan },
  passwordViewStyles: {
    flexDirection: 'row',
    height: moderateScale(45),
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: moderateScale(17),
    width: '80%',
    borderRadius: moderateScale(6),
    borderWidth: moderateScale(0.8),
    borderColor: Colors.gray,
    backgroundColor: Colors.periwinkleGray,
  },
  passwordEyeStyles: {
    height: moderateScale(22),
    width: moderateScale(22),
  },
  passwordViewStylesFocus: {
    flexDirection: 'row',
    height: moderateScale(45),
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: moderateScale(17),
    width: '80%',
    borderRadius: moderateScale(6),
    borderWidth: moderateScale(1.2),
    borderColor: Colors.blue,
    backgroundColor: Colors.gallery,
  },
  emptyViewWhenNoPasswordIsEntered: {
    height: moderateScale(22),
    width: moderateScale(22),
  },
  passwordTextInput: {
    letterSpacing: 1,
    paddingHorizontal: 10,
    fontSize: moderateScale(18, 0.4),
    width: '100%',
    height: '100%',
  },

  loginStyles: {
    fontSize: moderateScale(20),
    color: Colors.white,
    fontWeight: '600',
  },
  disabledLoginStyles: {
    opacity: 0.3,
    fontSize: moderateScale(20),
    color: Colors.white,
    fontWeight: '600',
  },
  appLogoStyles: { width: moderateScale(90), height: moderateScale(64) },
  forgotPasswordStyles: { color: Colors.cyan, fontSize: moderateScale(16) },
  disabledLoginButtonStyles: {
    opacity: 0.3,
    height: moderateScale(35),
    borderRadius: moderateScale(6),
    justifyContent: 'center',
    alignItems: 'center',
    width: '55%',
    backgroundColor: Colors.natureGreen,
  },
  loginButtonStyles: {
    height: moderateScale(40),
    borderRadius: moderateScale(6),
    justifyContent: 'center',
    alignItems: 'center',
    width: '55%',
    backgroundColor: Colors.natureGreen,
  },
  emailTextInputStyles: {
    letterSpacing: 1,
    fontSize: moderateScale(18, 0.4),
    height: moderateScale(45),
    paddingHorizontal: moderateScale(10),
    padding: moderateScale(5),
    width: '80%',
    borderRadius: moderateScale(6),
    borderWidth: moderateScale(0.8),
    borderColor: Colors.gray,
    backgroundColor: Colors.periwinkleGray,
  },
  emailTextInputStylesFocus: {
    letterSpacing: 1,
    fontSize: moderateScale(18, 0.4),
    height: moderateScale(45),
    paddingHorizontal: moderateScale(10),
    padding: moderateScale(5),
    width: '80%',
    borderRadius: moderateScale(6),
    borderWidth: moderateScale(1.2),
    borderColor: Colors.blue,
    backgroundColor: Colors.gallery,
  },
  keyboardAvoidingViewStyles: {
    width: '100%',
    height: '70%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors.darkBlue,
  },
  viewWithHeightForty: { height: moderateScale(40) },
  viewWithHeightThirty: { height: moderateScale(30) },
  viewWithHeightTwenty: { height: moderateScale(20) },
  viewWithHeightTen: { height: moderateScale(10) },
  loadingScreen: {
    zIndex: 20,
    backgroundColor: 'rgba(150,150,150,0.5)',
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
  },
});

export default styles;
