const images = {
  menuIcon: require('./menu.png'),
  searchIcon: require('./magnifyingGlass.png'),
  appLogo: require('./tmdbLogo.png'),
  expandArrow: require('./expandArrow.png'),
  play: require('./playDetails.png'),
  playTrailer: require('./playTrailer.png'),
  back: require('./back.png'),
  expandArrowBlue: require('./expandArrowBlue.png'),
  saveOutline: require('./bookmarkOutline.png'),
  saveFilled: require('./bookmarkFilled.png'),
  saveLime: require('./bookmarkLime.png'),
  youtube: require('./youtube.png'),
  logout: require('./logoutLight.png'),
  topRated: require('./topRated.png'),
  topRatedLime: require('./topRatedLime.png'),
  home: require('./home.png'),
  homeLime: require('./homeLime.png'),
  heartOutline: require('./heartOutline.png'),
  heartFilled: require('./heartFilled.png'),
  star: require('./star.png'),
  eye: require('./passwordEye.png'),
  invisibleEye: require('./passwordInvisible.png'),
  profile: require('./profile.png'),
  profileLime: require('./profileLime.png'),
  shrug: require('./shrug.png'),
  close: require('./close.png'),
  tick: require('./tick.png'),
  balloon: require('./balloon.png'),
  google: require('./google.png'),
};

export default images;
