export default {
  search: require('./search.png'),
  drawer: require('./drawer.png'),
  back: require('./back.png'),
  user: require('./user.png'),
  more: require('./more.png'),
  expand: require('./expand.png'),
  play: require('./play.png'),
  home: require('./home.png'),
  login: require('./login.png'),
  logout: require('./logout.png'),
  people: require('./people.png'),
  trending: require('./trending.png'),
  tv: require('./tv.png'),
  trailers: require('./trailers.png'),
  movie: require('./movie.png'),
  community: require('./community.png'),
  eye: require('./passwordEye.png'),
  invisibleEye: require('./passwordInvisible.png'),
  cancel: require('./cancel.png'),
  noData: require('./noData.png'),
};
