const strings = {
  popularNow: 'Popular Now',
  popularTV: 'Popular TV',
  topRated: 'Top Rated',
  watchList: 'WatchList',
  emptyWatchList: 'WatchList is Empty',
  myRatings: 'My Ratings',
  notHaveRatedYet: 'You have not rated Anything yet!',
  oops: 'OOPS!',
  recheckEmailAndPass: 'Please recheck you email and password',
  OK: 'OK',
  homeScreenTitle: 'MovieDB',
  homeScreenNavigationButtonTitle: 'Go to next screen',
  movieDetailScreenText: 'Movie Detail',
  movieDetailNavigationButtonTitle: 'Go Back',
  percentSymbol: '%',
  whatsPopular: "What's Popular",
  freeToWatch: 'Free To Watch',
  today: 'Today',
  trending: 'Trending',
  errorMessage: "Sorry Couldn't fetch Data",
  streaming: 'Streaming',
  onTV: 'On TV',
  inTheatres: 'In Theatres',
  forRent: 'For Rent',
  userScore: 'User Score',
  playTrailer: 'Play Trailer',
  latestTrailers: 'Latest Trailers',
  nr: 'NR',
  us: 'US',
  overview: 'Overview',
  commaWithLeadingSpace: ', ',
  space: ' ',
  dotChar: ' • ',
  errorMessageDetailScreen: 'Could not fetch data, please try again',
  dummyDate: '01/01/2000',
  zero: '0',
  one: '01',
  two: '02',
  three: '03',
  four: '04',
  five: '05',
  six: '06',
  seven: '07',
  eight: '08',
  nine: '09',
  ten: '10',
  eleven: '11',
  twelve: '12',
  january: 'Jan',
  february: 'Feb',
  march: 'March',
  april: 'April',
  may: 'May',
  june: 'June',
  july: 'July',
  august: 'August',
  september: 'September',
  october: 'October',
  november: 'November',
  december: 'December',
  nil: 'nil',
  h: 'h',
  m: 'm',
  defaultText: 'Default Text',
  NetworkErrorMessage: 'Please check your internet connection',
  ServerNotAvailable: 'Server is not available',
  SomethingWrong: 'Something went wrong',
  NetworkError: 'NETWORK_ERROR',
  ConnectionError: 'CONNECTION_ERROR',
  ServerError: 'SERVER_ERROR',
  director: 'Director',
  tv: 'tv',
  movie: 'movie',
  directing: 'Directing',
  popular: 'Popular',
  latestTrailer: 'LatestTrailer',
  freeToWatchs: 'FreeToWatch',
  trendings: 'Trending',
  login: 'Log in',
  logout: 'Logout',
  dontHaveAccount: "Don't have an account? ",
  forgotPassword: 'forgot password?',
  enterPassword: 'enter password',
  enterEmail: 'enter email',
  signUp: 'Sign Up',
  passwordValidation:
    'Password must contain at least 8 characters, including UPPER/lowercase letters and numbers.',
  createAccount: 'Create an account',
  alreadyHaveAccount: 'Already have an account? ',
  createStrongPassword: 'Please create a strong password!',
  topSearch: "Today's Top Searches",
  noDataFound: "Sorry, couldn't find any result matching",
  searchRecommend: 'Recommended Free To Watch',
  brief: 'Brief',
  popularity: 'Popularity',
  moviesToWatch: 'Movies to watch',
  language: 'Language : ',
  date: 'Date : ',
  addToFavorites: 'Add to favorites',
  addedToFavorites: 'Added to favorites',
  name: 'Name',
  username: 'Username',
  about: 'About',
  showFavorite: 'Show favorite',
  addYourBirthday: 'Add your birthday',
  editProfile: 'Edit Profile',
  myProfile: 'My Profile',
  warning: 'Warning',
  cannotChangeDOBLater: 'You cannot change your Date of Birth Later',
  cancel: 'cancel',
  ok: 'ok',
  sorry: 'Sorry!',
  adultContentWarning:
    'The following media is intended only for audience over 18+',
  watch: 'Watch',
  trailer: 'trailer',
  googleSignInFail: 'Some Error occurred. Please try again Later',
  sendCode: 'Send Code',
  confirm: 'Confirm',
  indiaCountryCode: '+91',
  invalidPhone: 'Invalid Phone number',
  invalidCode: 'Invalid code',
  enterPhoneNumber: 'Enter phone number',
  enterOTP: 'Enter OTP',
  movieStars: 'Movie Stars',
  male: 'Male',
  female: 'Female',
  seeFilmography: 'See filmography',
  celebrity: 'celebrity',
  message: 'Message',
  online: 'online',
  lastSeen: 'last seen',

  //Screen Names
  loginScreen: 'LoginScreen',
  phoneNumberScreen: 'PhoneNumberScreen',
  genreListScreen: 'GenreList',
  genreMovies: 'GenreMovies',
  detailScreen: 'Detail',
  home: 'Home',
  ratedByMe: 'Rated By Me',
  community: 'Community',
  genres: 'Genres',
  peopleListScreen: 'PeopleList',
  people: 'People',
  celebrityDetailScreen: 'CelebrityDetailScreen',
  chatScreen: 'ChatScreen',
  communityScreen: 'CommunityScreen',
  otherProfile: 'OtherProfile',
};

export default strings;
