const strings = {
  homeScreenTitle: 'MovieDB',
  homeScreenNavigationButtonTitle: 'Go to next screen',
  movieDetailScreenText: 'Movie Detail',
  movieDetailNavigationButtonTitle: 'Go Back',
  percentSymbol: '%',
  whatsPopular: "What's Popular",
  freeToWatch: 'Free To Watch',
  today: 'Today',
  trending: 'Trending',
  errorMessage: "Sorry Couldn't fetch Data",
  streaming: 'Streaming',
  onTV: 'On TV',
  inTheatres: 'In Theatres',
  forRent: 'For Rent',
  userScore: 'User Score',
  playTrailer: 'Play Trailer',
  latestTrailers: 'Latest Trailers',
  nr: 'NR',
  us: 'US',
  overview: 'Overview',
  commaWithLeadingSpace: ', ',
  space: ' ',
  dotChar: ' • ',
  errorMessageDetailScreen: 'Could not fetch data, please try again',
  dummyDate: '01/01/2000',
  zero: '0',
  one: '01',
  two: '02',
  three: '03',
  four: '04',
  five: '05',
  six: '06',
  seven: '07',
  eight: '08',
  nine: '09',
  ten: '10',
  eleven: '11',
  twelve: '12',
  january: 'Jan',
  february: 'Feb',
  march: 'March',
  april: 'April',
  may: 'May',
  june: 'June',
  july: 'July',
  august: 'August',
  september: 'September',
  october: 'October',
  november: 'November',
  december: 'December',
  nil: 'nil',
  h: 'h',
  m: 'm',
};

export default strings;
